### ISSUE TITLE
Can you add fix to whitespace characters? (have solution)

### ISSUE THREAD

**Issue by XCanG** [zzzprojects/sqlfiddle3#18]
Right now if some text field have newlines or spaces, they are collapsed, to fix that you simply need to add this rule to CSS:
```CSS
.table td {
	white-space: pre;
}
```
